name: Test with testcontainer

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      options: --platform linux/amd64

    services:
      docker:
        image: docker:24.0.7-dind
        options: --privileged
        ports:
          - 2375:2375

    env:
      DOCKER_HOST: tcp://localhost:2375

