name: Test with testcontainer

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  services:
    docker:
      image: docker:24.0.7-dind
      options: --privileged
      ports:
        - 2375:2375

  env:
    DOCKER_HOST: tcp://localhost:2375

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Start docker.
      run: |
        sudo systemctl start docker
        docker info

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./logic -v
