name: Test with testcontainer

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      options: --platform linux/amd64

    services:
      docker:
        image: docker:24.0.7-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: unix:///var/run/docker.sock

    env:
      DOCKER_HOST: unix:///var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify docker
        run: docker ps 

      - name: Setup Go.
        uses: actions/setup-go@v5
        with:
          go-version: 1.23 

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod 
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go Dependencies
        run: go mod tidy && go mod download

      - name: Cache Docker Layers for the Test Containers.
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Load Cached docker layers.
        run: |
          mkdir -p /tmp/.buildx-cache
          docker buildx create --use --driver docker-container --buildkitd-flags "--debug"
          docker buildx inspect --bootstrap

      - name: Run tests
        run: go test ./logic -v
